### ISSUE TITLE
timelogging broken since 2021-03-03

### ISSUE THREAD

**Issue by manfred-ackermann** [RindusIoTJam/personio-timelogger#11]
```
 acki@vm209  ~/bin  ~/bin/personio-timelogger.py 2021-03-03
Traceback (most recent call last):
  File "/home/acki/bin/personio-timelogger.py", line 156, in <module>
    urlOpener.open(ATTENDANCE_URL, data=bytes(json.dumps(attendance_entry), 'utf-8'))
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by manfred-ackermann** [comment]
installing Python 3.7 and enforcing use of it and

```
python3.7 -m pip install requests
git checkout e5c44c3f97eaa55c618a3ce7cd102eba71c73828
```

fixes the issue.
